# Generated by Django 5.1.4 on 2024-12-27 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="用户ID",
                    ),
                ),
                ("password", models.CharField(max_length=100, verbose_name="密码")),
                (
                    "identity",
                    models.CharField(
                        choices=[
                            ("管理员", "管理员"),
                            ("教师", "教师"),
                            ("学生", "学生"),
                        ],
                        max_length=100,
                        verbose_name="身份",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户信息",
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "class_id",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="班级ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=100, verbose_name="班级名")),
            ],
            options={
                "verbose_name": "班级表",
                "verbose_name_plural": "班级表",
                "db_table": "class",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "cour_id",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="课程ID",
                    ),
                ),
                ("cour_name", models.CharField(max_length=100, verbose_name="课程名")),
                ("cour_credits", models.FloatField(verbose_name="学分")),
                (
                    "cour_semester",
                    models.CharField(max_length=100, verbose_name="开设学期"),
                ),
            ],
            options={
                "verbose_name": "课程表",
                "verbose_name_plural": "课程信息",
                "db_table": "course",
            },
        ),
        migrations.CreateModel(
            name="CoursePlan",
            fields=[
                (
                    "plan_id",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="计划ID",
                    ),
                ),
                (
                    "plan_content",
                    models.CharField(max_length=1000, verbose_name="内容"),
                ),
                ("plan_submittime", models.DateTimeField(verbose_name="提交时间")),
            ],
            options={
                "verbose_name": "课程计划表",
                "verbose_name_plural": "课程计划表",
                "db_table": "courseplan",
            },
        ),
        migrations.CreateModel(
            name="Depart",
            fields=[
                (
                    "depart_id",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="院系ID",
                    ),
                ),
                (
                    "depart_name",
                    models.CharField(max_length=100, verbose_name="院系名"),
                ),
            ],
            options={
                "verbose_name": "院系表",
                "verbose_name_plural": "院系表",
                "db_table": "depart",
            },
        ),
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "major_id",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="专业ID",
                    ),
                ),
                ("major_name", models.CharField(max_length=100, verbose_name="专业名")),
            ],
            options={
                "verbose_name": "专业表",
                "verbose_name_plural": "专业表",
                "db_table": "major",
            },
        ),
        migrations.CreateModel(
            name="Semesters",
            fields=[
                (
                    "semester",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="学期",
                    ),
                ),
            ],
            options={
                "verbose_name": "学期表",
                "verbose_name_plural": "学期",
                "db_table": "semester",
            },
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "admin_id",
                    models.OneToOneField(
                        db_column="admin_id",
                        max_length=100,
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="admins.user",
                        verbose_name="管理员ID",
                    ),
                ),
                (
                    "admin_name",
                    models.CharField(max_length=100, verbose_name="管理员姓名"),
                ),
                (
                    "admin_phnum",
                    models.CharField(max_length=20, verbose_name="联系电话"),
                ),
            ],
            options={
                "verbose_name": "管理员",
                "verbose_name_plural": "管理员信息",
                "db_table": "admin",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "stu_id",
                    models.OneToOneField(
                        db_column="stu_id",
                        max_length=100,
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="admins.user",
                        verbose_name="学生ID",
                    ),
                ),
                ("stu_name", models.CharField(max_length=100, verbose_name="学生姓名")),
                (
                    "stu_phnum",
                    models.CharField(max_length=100, verbose_name="联系电话"),
                ),
                (
                    "stu_semester",
                    models.ForeignKey(
                        db_column="stu_semester",
                        max_length=100,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admins.semesters",
                        verbose_name="年级",
                    ),
                ),
            ],
            options={
                "verbose_name": "学生表",
                "verbose_name_plural": "学生信息",
                "db_table": "student",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "tch_id",
                    models.OneToOneField(
                        db_column="tch_id",
                        max_length=100,
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="admins.user",
                        verbose_name="教师ID",
                    ),
                ),
                ("tch_name", models.CharField(max_length=100, verbose_name="教师姓名")),
                (
                    "tch_phnum",
                    models.CharField(max_length=100, verbose_name="联系电话"),
                ),
            ],
            options={
                "verbose_name": "教师",
                "verbose_name_plural": "教师信息",
                "db_table": "teacher",
            },
        ),
        migrations.CreateModel(
            name="StudentMajor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "major_id",
                    models.ForeignKey(
                        db_column="major_id",
                        max_length=100,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admins.major",
                        verbose_name="专业ID",
                    ),
                ),
                (
                    "stu_id",
                    models.ForeignKey(
                        db_column="stu_id",
                        max_length=100,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admins.student",
                        verbose_name="学生ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "学生专业关联表",
                "verbose_name_plural": "学生专业关联表",
                "db_table": "studentmajor",
            },
        ),
        migrations.CreateModel(
            name="StudentClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_id",
                    models.ForeignKey(
                        db_column="class_id",
                        max_length=100,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admins.class",
                        verbose_name="班级ID",
                    ),
                ),
                (
                    "stu_id",
                    models.ForeignKey(
                        db_column="stu_id",
                        max_length=100,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admins.student",
                        verbose_name="学生ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "学生班级关联表",
                "verbose_name_plural": "学生班级关联表",
                "db_table": "studentclass",
            },
        ),
        migrations.CreateModel(
            name="WaiverApplication",
            fields=[
                (
                    "wa_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="免听申请ID"
                    ),
                ),
                ("reason", models.CharField(max_length=500, verbose_name="申请理由")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("未审核", "未审核"),
                            ("审核中", "审核中"),
                            ("同意", "同意"),
                            ("否决", "否决"),
                        ],
                        default="未审核",
                        max_length=100,
                        verbose_name="状态",
                    ),
                ),
                (
                    "cour_id",
                    models.ForeignKey(
                        db_column="cour_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admins.course",
                        verbose_name="课程ID",
                    ),
                ),
                (
                    "stu_id",
                    models.ForeignKey(
                        db_column="stu_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admins.student",
                        verbose_name="学生ID",
                    ),
                ),
                (
                    "tch_id",
                    models.ForeignKey(
                        db_column="tch_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admins.teacher",
                        verbose_name="教师ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "免听申请表",
                "verbose_name_plural": "免听申请表",
                "db_table": "waiverapplication",
            },
        ),
        migrations.CreateModel(
            name="TeacherCourse_1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cour_id",
                    models.ForeignKey(
                        db_column="cour_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admins.course",
                        verbose_name="课程ID",
                    ),
                ),
                (
                    "tch_id",
                    models.ForeignKey(
                        db_column="tch_id",
                        max_length=100,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admins.teacher",
                        verbose_name="教师ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "教师课程关联表",
                "verbose_name_plural": "教师课程关联表",
                "db_table": "teachercourse",
            },
        ),
        migrations.CreateModel(
            name="CourseAdapt",
            fields=[
                (
                    "ca_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="调课申请ID"
                    ),
                ),
                ("week", models.CharField(max_length=100, verbose_name="第几周")),
                (
                    "classroom",
                    models.CharField(max_length=100, verbose_name="上课地点"),
                ),
                ("dayofweek", models.CharField(max_length=100, verbose_name="周几")),
                ("timeslot", models.CharField(max_length=100, verbose_name="时间段")),
                ("reason", models.CharField(max_length=500, verbose_name="申请理由")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("未审核", "未审核"),
                            ("同意", "同意"),
                            ("否决", "否决"),
                        ],
                        default="未审核",
                        max_length=100,
                        verbose_name="状态",
                    ),
                ),
                (
                    "cour_id",
                    models.ForeignKey(
                        db_column="cour_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admins.course",
                        verbose_name="课程ID",
                    ),
                ),
                (
                    "tch_id",
                    models.ForeignKey(
                        db_column="tch_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admins.teacher",
                        verbose_name="教师ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "调课申请表",
                "verbose_name_plural": "调课申请表",
                "db_table": "courseadapt",
            },
        ),
        migrations.CreateModel(
            name="TeacherDepart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "depart_id",
                    models.ForeignKey(
                        db_column="depart_id",
                        max_length=100,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admins.depart",
                        verbose_name="院系ID",
                    ),
                ),
                (
                    "tch_id",
                    models.ForeignKey(
                        db_column="tch_id",
                        max_length=100,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admins.teacher",
                        verbose_name="教师ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "教师院系关联",
                "verbose_name_plural": "教师院系关联表",
                "db_table": "teacherdepart",
                "unique_together": {("tch_id", "depart_id")},
            },
        ),
    ]
