# Generated by Django 5.1.4 on 2024-12-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherdepart',
            options={'verbose_name': '教师院系关联', 'verbose_name_plural': '教师院系关联表'},
        ),
        migrations.AddConstraint(
            model_name='teacherdepart',
            constraint=models.UniqueConstraint(fields=('tch_id', 'depart_id'), name='unique_teacher_depart'),
        ),
    ]
