# Generated by Django 5.1.4 on 2025-01-01 08:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User_log",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "user_name",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("user_pwd", models.CharField(max_length=128)),
                ("identify", models.CharField(max_length=30)),
                ("opaque_password", models.CharField(max_length=100)),
                ("last_login", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
